# Generated by Django 5.1.2 on 2024-12-06 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category_man", "0001_initial"),
        ("warehouse_man", "0002_alter_warehouse_slug_alter_warehouse_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category", unique_together={("user", "warehouse", "slug")},
        ),
    ]
