# Generated by Django 5.1.2 on 2024-12-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category_man", "0002_alter_category_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category", name="slug", field=models.SlugField(blank=True),
        ),
    ]
