# Generated by Django 5.1.2 on 2024-12-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=50)),
                ("warehouse_limit", models.PositiveIntegerField(default=1)),
                ("category_per_warehouse", models.PositiveIntegerField(default=3)),
                ("products_per_category", models.PositiveIntegerField(default=20)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
    ]
