# Generated by Django 5.1.2 on 2024-12-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_plans", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="category_per_warehouse",
            new_name="category_per_warehouse_limit",
        ),
        migrations.RenameField(
            model_name="plan",
            old_name="products_per_category",
            new_name="products_per_category_limit",
        ),
    ]
