# Generated by Django 5.1.2 on 2024-12-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts_plans",
            "0002_rename_category_per_warehouse_plan_category_per_warehouse_limit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="plan_description",
            field=models.TextField(blank=True, default="---"),
        ),
    ]
