# Generated by Django 5.1.2 on 2024-12-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_plans", "0004_plan_is_default_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan", name="slug", field=models.SlugField(blank=True),
        ),
    ]
