# Generated by Django 5.1.2 on 2024-12-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_plans", "0005_plan_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="plan", name="slug",),
    ]
