# Generated by Django 5.1.2 on 2024-12-19 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse_man", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
