# Generated by Django 5.1.2 on 2024-12-06 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse_man", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse", name="slug", field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name="warehouse", unique_together={("user", "slug")},
        ),
    ]
