# Generated by Django 5.1.2 on 2024-12-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse_man", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="neighborhood",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="street",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
