# Generated by Django 5.1.2 on 2024-12-18 13:18

import django.db.models.deletion
import inventory_man.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_man', '0001_initial'),
        ('warehouse_man', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_image",
                    models.ImageField(
                        blank=True,
                        default="images/item_images/default_image.jpg",
                        null=True,
                        upload_to=inventory_man.models.InventoryItem.image_upload_to,
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("ltr", "Litre"),
                            ("pcs", "Pieces"),
                            ("box", "Box"),
                        ],
                        default="pcs",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Turkish Liras"),
                            ("USD", "United States Dollars"),
                            ("EUR", "Euro"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                ("description", models.TextField(blank=True, default="---")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category_man.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse_man.warehouse",
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Inventory Items',
                'unique_together': {('user', 'warehouse', 'category', 'slug')},
            },
        ),
    ]
