# Generated by Django 5.1.2 on 2024-12-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_man", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="description",
            field=models.TextField(blank=True, default="---"),
        ),
    ]
