# Generated by Django 5.1.2 on 2024-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_man", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="item_image",
            field=models.ImageField(
                blank=True,
                default="images/item_images/default_image.jpg",
                null=True,
                upload_to="images/item_images/",
            ),
        ),
    ]
