# Generated by Django 5.1.2 on 2024-11-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_man", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
    ]
