# Generated by Django 5.1.2 on 2024-12-18 12:01

import inventory_man.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_man", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="item_image",
            field=models.ImageField(
                blank=True,
                default="images/item_images/default_image.jpg",
                null=True,
                upload_to=inventory_man.models.InventoryItem.image_upload_to,
            ),
        ),
    ]
