# Generated by Django 5.1.2 on 2024-12-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_man", "0002_alter_inventoryitem_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TRY", "Turkish Liras"),
                    ("USD", "United States Dollars"),
                    ("EUR", "Euro"),
                ],
                default="TRY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogram"),
                    ("ltr", "Litre"),
                    ("pcs", "Pieces"),
                    ("box", "Box"),
                ],
                default="pcs",
                max_length=10,
            ),
        ),
    ]
